name: Build LaTeX Report

on:
  push:
    paths:
      - 'PullaguariAxel_InformeLaboratorio/**.tex'
      - 'PullaguariAxel_InformeLaboratorio/**.png'
      - 'PullaguariAxel_InformeLaboratorio/**.jpg'
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: PullaguariAxel_InformeLaboratorio/
          # Install extra packages if needed (e.g., for Spanish babel)
          extra_system_packages: "texlive-lang-spanish"

      - name: Rename PDF
        run: mv PullaguariAxel_InformeLaboratorio/main.pdf PullaguariAxel_InformeLaboratorio/PullaguariAxel_InformeLaboratorio.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Informe_Laboratorio_PDF
          path: PullaguariAxel_InformeLaboratorio/PullaguariAxel_InformeLaboratorio.pdf
